title: Product

options:
  preview: https://kirbycopilot.com

columns:
  - width: 2/3
    fields:
      manufacturer:
        label: Manufacturer
        type: text
        width: 1/3
      category:
        label: Category
        type: text
        width: 1/3
      releaseDate:
        label: Release Date
        type: date
        width: 1/3
  - width: 2/3
    fields:
      content01:
        label: Blocks
        type: blocks
  - width: 1/3
    sections:
      copilot01:
        type: copilot
        field: content01
      # files:
      #   label: Files
      #   type: files
      #   template: image
