title: Product

buttons:
  copilot: true
  preview: true
  settings: true
  status: true

tabs:
  content:
    label: Content
    columns:
      - width: 2/3
        fields:
          title:
            label: Product Name
            type: text
            help: The main product title

          description:
            label: Product Description
            type: textarea
            help: Detailed description highlighting key features and benefits

          features:
            label: Key Features
            type: structure
            fields:
              title:
                label: Feature Title
                type: text
                help: Brief feature name
              description:
                label: Feature Description
                type: textarea
                help: Detailed explanation of this feature
              icon:
                label: Icon
                type: text
                help: Icon name or emoji representing this feature
            help: List of product features and capabilities

          specifications:
            label: Technical Specifications
            type: textarea
            help: Technical details, dimensions, compatibility, etc.

          benefits:
            label: Customer Benefits
            type: list
            help: Key benefits customers will experience

      - width: 1/3
        fields:
          price:
            label: Price
            type: text
            help: Product pricing information

          category:
            label: Product Category
            type: select
            options:
              - Electronics
              - Software
              - Hardware
              - Accessories
              - Services
              - Tools
            help: Main product category

          tags:
            label: Product Tags
            type: tags
            help: Keywords for search and categorization

          availability:
            label: Availability Status
            type: select
            options:
              - In Stock
              - Limited Stock
              - Pre-order
              - Out of Stock
              - Discontinued
            default: In Stock

  marketing:
    label: Marketing
    fields:
      tagline:
        label: Marketing Tagline
        type: text
        help: Catchy one-liner for marketing materials

      targetAudience:
        label: Target Audience
        type: textarea
        help: Description of ideal customers and use cases

      competitiveAdvantages:
        label: Competitive Advantages
        type: list
        help: What sets this product apart from competitors

      useCases:
        label: Use Cases
        type: structure
        fields:
          scenario:
            label: Use Case Scenario
            type: text
            help: Brief title of the use case
          description:
            label: Description
            type: textarea
            help: Detailed explanation of how the product solves this scenario
          targetUser:
            label: Target User
            type: text
            help: Who would use the product in this scenario
        help: Real-world scenarios where this product excels

  seo:
    label: SEO & Metadata
    fields:
      metaTitle:
        label: Meta Title
        type: text
        help: SEO-optimized title for search engines

      metaDescription:
        label: Meta Description
        type: textarea
        maxlength: 160
        help: Compelling description for search results

      keywords:
        label: SEO Keywords
        type: tags
        help: Target keywords for search optimization
