title: Recipe

buttons:
  copilot: true
  open: true
  settings: true
  status: true

tabs:
  content:
    label: Content
    columns:
      - width: 2/3
        fields:
          instructions:
            label: Cooking Instructions
            type: writer
            toolbar:
              inline: false
            marks:
              - bold
              - italic
              - underline
              - strike
              - code
              - "|"
              - link
              - email
              - "|"
              - clear
              - "|"
              - copilot
              - copilot-suggestions
            help: Step-by-step cooking instructions with rich formatting

          ingredients:
            label: Ingredients
            type: structure
            fields:
              amount:
                label: Amount
                type: text
                width: 1/4
                help: e.g., 2 cups, 1 tbsp
              ingredient:
                label: Ingredient
                type: text
                width: 1/2
                help: The ingredient name
              notes:
                label: Notes
                type: text
                width: 1/4
                help: Optional preparation notes
            help: List all ingredients with measurements

      - width: 1/3
        fields:
          description:
            label: Recipe Description
            type: textarea
            help: A mouth-watering introduction to this recipe
            buttons:
              - copilot

          recipeInfo:
            label: Recipe Details
            type: group
            fields:
              servings:
                label: Servings
                type: number
                default: 4
                help: Number of servings this recipe yields
              prepTime:
                label: Prep Time
                type: text
                help: e.g., 15 minutes
              cookTime:
                label: Cook Time
                type: text
                help: e.g., 30 minutes
              difficulty:
                label: Difficulty Level
                type: select
                options:
                  - Easy
                  - Medium
                  - Advanced
                  - Expert
                default: Medium
