title: Playground

buttons:
  copilot: true
  social:
    icon: cart
    text: Buy
    link: https://kirby.tools/copilot/buy
    theme: love-icon

tabs:
  gettingStarted:
    label: Getting Started
    columns:
      - width: 2/3
        fields:
          infoWelcome:
            label: Welcome to Kirby Copilot
            type: info
            theme: positive
            text: |
              Choose your favorite AI provider below to play with **Kirby Copilot**. An API key is required to try this playground. For production use of the plugin, you can store the API key in Kirby's configuration file.

              **Get your API key:**
              - **OpenAI**: [platform.openai.com/api-keys](https://platform.openai.com/api-keys)
              - **Google**: [aistudio.google.com/app/apikey](https://aistudio.google.com/app/apikey)
              - **Anthropic**: [console.anthropic.com/settings/keys](https://console.anthropic.com/settings/keys)

          headlineProvider:
            type: headline
            label: AI Provider Configuration
            numbered: false

          modelProvider:
            label: AI Provider
            type: toggles
            default: openai
            grow: false
            options:
              - value: openai
                text: OpenAI
                icon: copilot-provider-openai
              - value: google
                text: Google
                icon: copilot-provider-google
              - value: anthropic
                text: Anthropic
                icon: copilot-provider-anthropic
            help: Choose your preferred AI provider. We recommend **Google** with their Gemini models. You can create an API key [for free](https://aistudio.google.com/app/apikey).

          apiKey:
            label: API Key
            type: playground-api-key
            help: |
              The key is stored securely in your browser's session storage.

          openaiModel:
            label: Model
            type: select
            when:
              modelProvider: openai
            options:
              o4-mini: o4-mini (recommended)
              gpt-4o: GPT-4o
              gpt-4o-mini: GPT-4o Mini
            help: o4-mini offers a good balance of performance and cost. Blocks generation is weak for all OpenAI models.

          googleModel:
            label: Model
            type: select
            when:
              modelProvider: google
            options:
              gemini-2.5-flash: Gemini 2.5 Flash (recommended)
              gemini-2.5-pro: Gemini 2.5 Pro
            help: Gemini 2.5 Flash excels at structured content generation. Our overall recommendation!

          anthropicModel:
            label: Model
            type: select
            when:
              modelProvider: anthropic
            options:
              claude-sonnet-4-20250514: Claude 4 Sonnet (recommended)
              claude-opus-4-20250514: Claude 4 Opus
            help: Claude 4 Sonnet provides excellent reasoning and creativity.

      - width: 1/3
        fields:
          infoInstallation:
            label: 🙋‍♂️ Curious? Try in your project!
            type: info
            theme: passive
            text: |
              **<sparkly-text style="--sparkly-text-size: 2em; --sparkly-text-color: var(--color-yellow-600)">[Install Kirby Copilot](https://kirby.tools/docs/copilot/getting-started/installation)</sparkly-text>** now in your own projects, and buy a license when you're convinced.

  blocksFields:
    label: Blocks Fields
    columns:
      - width: 1/1
        fields:
          headlineBlocks:
            type: headline
            label: Blocks Field Generation
            numbered: false

      - width: 2/3
        fields:
          demoBlocks:
            extends: fields/blocks
            label: Blocks Builder
            help: |
              Copilot generates content **based on your blocks** definitions and fieldsets.<br> It adapts to your project's structure!

      - width: 1/3
        sections:
          copilotBlocks:
            type: copilot
            field: demoBlocks
            userPrompt: Create an engaging landing page for the Kirby CMS. Showcase what it offers for designers and developers.
            open: true

  layoutFields:
    label: Layout Fields
    columns:
      - width: 1/1
        fields:
          headlineLayouts:
            type: headline
            label: Layout Field Generation
            numbered: false

      - width: 2/3
        fields:
          demoLayouts:
            label: Layout Builder
            type: layout
            layouts:
              - 1/1
              - 1/2, 1/2
              - 1/3, 2/3
              - 2/3, 1/3
            fieldsets:
              # Landing page blocks
              - hero
              - features
              - showcase
              # - stats
              - testimonials
              - team
              # - pricing
              - faq
              - cta
              - contact
              # # Core Kirby blocks
              - heading
              - text
              # - list
              # - quote
              # - image
              # - video
              # - code
              # - markdown
            help: |
              Copilot generates content **based on your blocks** definitions and fieldsets.<br> It adapts to your project's structure!

      - width: 1/3
        sections:
          copilotLayouts:
            type: copilot
            field: demoLayouts
            userPrompt: Create a modern landing page for the Kirby CMS with hero section, features, testimonials, and call-to-action. Showcase what it offers for designers and developers.
            open: true

          infoLayoutTip:
            label: Required Models
            type: info
            theme: notice
            text: |
              Please use **Google Gemini** models, since OpenAI's models have [limitations on nested structured outputs](https://platform.openai.com/docs/guides/structured-outputs/supported-schemas?api-mode=responses#objects-have-limitations-on-nesting-depth-and-size). Gemini models have superior structured output capabilities.

  textFields:
    label: Writer & Textareas
    columns:
      - width: 1/1
        fields:
          infoText:
            label: Toolbar and Shortcuts
            type: info
            theme: positive
            text: |
              Writer and textarea fields support two interaction modes:
              - Use the Copilot section on the right, just like with blocks fields.
              - Use the toolbar button to open a prompt dialog. To open it programmatically, use the shortcut:
                `Cmd + .` (macOS) or `Ctrl + .` (Windows/Linux).

          headlineWriter:
            type: headline
            label: Writer Fields
            numbered: false

      - width: 2/3
        fields:
          demoWriter:
            label: Text
            type: writer
            toolbar:
              inline: false
            marks:
              - bold
              - italic
              - underline
              - "|"
              - copilot

      - width: 1/3
        sections:
          copilotWriter:
            type: copilot
            field: demoWriter
            userPrompt: Write a compelling introduction about the future of web development.

      - width: 1/1
        fields:
          headlineTextarea:
            type: headline
            label: Textarea Fields
            numbered: false

      - width: 2/3
        fields:
          demoTextarea:
            label: Text
            type: textarea
            buttons:
              - headlines
              - "|"
              - bold
              - italic
              - "|"
              - copilot

      - width: 1/3
        sections:
          copilotTextarea:
            type: copilot
            field: demoTextarea

  context:
    label: Placeholders
    columns:
      - width: 2/3
        fields:
          headlineContext:
            type: headline
            label: Context & Placeholders
            numbered: false

          infoContext:
            label: Info
            type: info
            theme: passive
            text: |
              Context is key to a good user prompt. You can access every fields of the same Panel view in your user prompts. Wrap the field name in curly braces to use it as a placeholder, for example `{siteTitle}`.

      - width: 2/3
        fields:
          contextDemo:
            label: Context Example
            type: blocks
            fieldsets:
              - heading
              - text
              - list
              - quote
              - image
              - video
              - code
              - markdown

          siteTitle:
            label: Site Title
            type: text
            width: 1/2
            help: Referenced in AI prompts as `{siteTitle}`

          currentYear:
            label: Current Year
            type: text
            width: 1/2
            help: Referenced in AI prompts as `{currentYear}`

      - width: 1/3
        sections:
          copilotContext:
            type: copilot
            field: contextDemo
            userPrompt: |
              Create content for {siteTitle} that's relevant for {currentYear}.

              Make it modern and engaging for today's audience.
            files: false
            open: true
            help: This prompt uses context from the **Site Title** and **Current Year** fields.
