title: Playground

options:
  preview: https://kirbycopilot.com

tabs:
  gettingStarted:
    label: Getting Started & Blocks
    columns:
      - width: 2/3
        fields:
          infoApiKey:
            label: Getting Started
            type: info
            theme: positive
            text: |
              To play with the **Kirby Copilot**, please enter your [OpenAI API key](https://platform.openai.com/api-keys) in the field below. If you don't have an API key yet, you can register for the [OpenAI API](https://platform.openai.com). The key is required to make client-side requests to GPT models. For production use of the plugin, you will need to provide one in the global configuration of Kirby.
          apiKey:
            label: OpenAI API Key
            type: playground-api-key
            help: |
              The key will be saved to the **session storage** of your browser. It will not be stored server-side or in any other way.
          gptModel:
            label: GPT Model
            type: select
            options:
              gpt-4o: GPT-4o (recommended)
              gpt-4o-mini: GPT-4o Mini
              gpt-3.5-turbo: GPT-3.5 Turbo (deprecated)
            help: |
              The GPT AI model to use in the Copilot playground. <ins>**Note: GPT-4 models will not work without a valid payment method in your account.**</ins>
      - width: 1/3
        fields:
          infoDocumentation:
            label: 🛍️ Convinced? Grab a copy!
            type: info
            theme: passive
            text: |
              Purchase a copy of <sparkly-text style="--sparkly-text-size: 2em; --sparkly-text-color: var(--color-yellow-600)">**Kirby Copilot**</sparkly-text> to improve the content management of your client's Kirby project or your own with AI.

      - width: 1/1
        fields:
          headline01:
            type: headline
            label: Copilot for Blocks Fields
      - width: 2/3
        fields:
          content01:
            label: Blocks
            type: blocks
      - width: 1/3
        sections:
          copilot01:
            type: copilot
            field: content01

  textlikeFields:
    label: Writer & Textarea Fields
    columns:
      - width: 1/1
        fields:
          infoTextlikeFields:
            label: Text-like Fields
            type: info
            theme: positive
            text: |
              Writer and textarea fields support two types of text generation:
              - Use the Copilot section on the right, just like with blocks fields.
              - Use the toolbar button to open a prompt dialog. To open it programmatically, use the shortcut: `Cmd + .` (macOS) or `Ctrl + .` (Windows/Linux).
          headline06:
            type: headline
            label: Copilot for Writer Fields
      - width: 2/3
        fields:
          content06:
            label: Writer
            type: writer
            toolbar:
              inline: false
            marks:
              - bold
              - italic
              - underline
              - "|"
              - clear
              - "|"
              - copilot
      - width: 1/3
        sections:
          copilot06:
            type: copilot
            field: content06

      - width: 1/1
        fields:
          headline02:
            type: headline
            label: Copilot for Textarea Fields
      - width: 2/3
        fields:
          content02:
            label: Textarea
            type: textarea
            buttons:
              - headlines
              - "|"
              - bold
              - italic
              - "|"
              - copilot
      - width: 1/3
        sections:
          copilot02:
            type: copilot
            field: content02
            systemPrompt: Provide responses in plain text.

  promptUsage:
    label: Prompt Usage
    columns:
      - width: 1/1
        fields:
          headline05:
            type: headline
            label: Include Fields as Context
      - width: 2/3
        fields:
          info05:
            label: Info
            type: info
            theme: passive
            text: |
              Context is key to a good user prompt. The content from other fields of the same model are available in the user prompt. Wrap the field name in curly braces to use it as a placeholder.

              This prompt uses the field `date` from the bottom of this page:
              ```
              What is the current date? (Hint, it is {date}!)
              ```
          content05:
            label: Blocks
            type: blocks
      - width: 1/3
        sections:
          copilot05:
            type: copilot
            field: content05
            userPrompt: |
              What is the current date?
              (Hint, it is {date}!)
            files: false

      - width: 1/1
        fields:
          headline03:
            type: headline
            label: Predefined Prompt
      - width: 2/3
        fields:
          info03:
            label: Info
            type: info
            theme: passive
            text: |
              Add a predefined user prompt with the `userPrompt` property.
          content03:
            label: Blocks
            type: blocks
      - width: 1/3
        sections:
          copilot03:
            type: copilot
            field: content03
            userPrompt: Write a short story about lorem ipsum. Segment article into headings (H2).

      - width: 1/1
        fields:
          headline04:
            type: headline
            label: Immutable, Predefined Prompt
      - width: 2/3
        fields:
          info04:
            label: Info
            type: info
            theme: passive
            text: |
              With both the `editable` and the `files` property set to `false`, the user prompt is not editable and no context files can be added, respectively.
          content04:
            label: Blocks
            type: blocks
      - width: 1/3
        sections:
          copilot04:
            type: copilot
            field: content04
            userPrompt: Write a short story about lorem ipsum. Segment article into headings (H2).
            editable: false
            files: false

      - width: 1/1
        fields:
          headlineContext:
            type: headline
            label: Context
      - width: 2/3
        fields:
          intro:
            label: Intro
            type: text
          infoContext:
            label: Info
            type: info
            theme: passive
            text: |
              Access the fields above in any user prompt by using the placeholders `{intro}` and `{date}`.
      - width: 1/3
        fields:
          date:
            label: Date
            type: date
